version=0.1
[default.deploy.parameters]
stack_name = "statsmodelService"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
tags = "project=\"statsmodelService\" stage=\"production\""