version=0.2
[default.deploy.parameters]
stack_name = "StatModelService"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
tags = "project=\"StatModelService\" stage=\"prod\""