AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A service to fit statistical models using 
  python package statsmodel and R formula
  model specification

Resources:
  predict:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: statsmodels/
      Handler: predict.lambda_handler
      MemorySize: 256
      Timeout: 300
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17' 
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:GetObject",
              "s3:ListBucket",
              "s3:GetBucketLocation",
              "s3:GetObjectVersion",
              "s3:GetLifecycleConfiguration"
            ],
            "Resource": [
              {
                "Fn::Sub": [
                  "arn:${AWS::Partition}:s3:::${bucketName}",
                  {
                    "bucketName": {
                      "Ref": "models"
                    }
                  }
                ]
              }
            ]
          }
        ]
      Runtime: python3.8
      Environment:
        Variables:
          bucket: !Ref models
          keyTemplate: fitted/{id}.pickle
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /predict
            Method: post
  fit:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: statsmodels/
      Handler: fit.lambda_handler
      MemorySize: 1024
      Timeout: 900
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17' 
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:PutObject",
              "s3:PutObjectAcl",
              "s3:PutLifecycleConfiguration"
            ],
            "Resource": [
              {
                "Fn::Sub": [
                  "arn:${AWS::Partition}:s3:::${bucketName}",
                  {
                    "bucketName": {
                      "Ref": "models"
                    }
                  }
                ]
              }
            ]
          }
        ]
      Runtime: python3.8
      Environment:
        Variables:
          bucket: !Ref models
          keyTemplate: fitted/{id}.pickle
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /fit
            Method: post

  models:
    Type: AWS::S3::Bucket

Outputs:
  statsmodelservicebucket:
    Description: bucket containing fitted models and model metadata
    Value: Value to return
  

