AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A service to fit statistical models using 
  python package statsmodel and R formula
  model specification

Resources:
  predict:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StatModelService/
      Handler: predict.lambda_handler
      MemorySize: 256
      Timeout: 300
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17' 
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:GetObject",
              "s3:ListBucket",
              "s3:GetBucketLocation",
              "s3:GetObjectVersion",
              "s3:GetLifecycleConfiguration"
            ],
            "Resource": [
              {
                "Fn::Sub": [
                  "arn:${AWS::Partition}:s3:::${bucketName}",
                  {
                    "bucketName": {
                      "Ref": "models"
                    }
                  }
                ]
              }
            ]
          }
        ]
      Runtime: python3.8
      Environment:
        Variables:
          bucket: !Ref models
          keyTemplate: fitted/{id}.pickle
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /predict
            Method: post
  fit:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StatModelService/
      Handler: fit.lambda_handler
      MemorySize: 1024
      Timeout: 900
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17' 
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:PutObject",
              "s3:PutObjectAcl",
              "s3:PutLifecycleConfiguration"
            ],
            "Resource": [
              {
                "Fn::Sub": [
                  "arn:${AWS::Partition}:s3:::${bucketName}",
                  {
                    "bucketName": {
                      "Ref": "models"
                    }
                  }
                ]
              }
            ]
          }
        ]
      Runtime: python3.8
      Environment:
        Variables:
          bucket: !Ref models
          keyTemplate: fitted/{id}.pickle
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /fit
            Method: post

  models:
    Type: AWS::S3::Bucket

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StatModelServiceS3Bucket:
    Description: "bucket containing fitted models and model metadata"
    Value: !Ref models
  StatModelServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for StatModelService"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  StatModelFitLambda:
    Description: "Fit Lambda Function ARN"
    Value: !GetAtt fit.Arn
  StatModelPredictLambda:
    Description: "Predict Lambda Function ARN"
    Value: !GetAtt predict.Arn
  StatModelFitIamRole:
    Description: "Implicit IAM Role created for StatModelFitLambda function"
    Value: !GetAtt fitRole.Arn
  StatModelFPredictIamRole:
    Description: "Implicit IAM Role created for StatModelPredictLambda function"
    Value: !GetAtt predictRole.Arn

